#!/bin/bash
IMAGES_DIRECTORY="../yocto/build_opcapsolo/tmp/deploy/images/icorem6solo/"

if [ ! -d ${IMAGES_DIRECTORY} ]
then
   zenity --error --text="You haven't built an image yet!" 
else
   nautilus ${IMAGES_DIRECTORY}
fi

exit 0
